#!/usr/bin/env python
import os
import socks
import socket
import httplib
import urllib
import urllib2
from urllib2 import URLError, HTTPError
import json
from copy import deepcopy
import base64
import time
import argparse
import requests
import febrc
import sys

parser = argparse.ArgumentParser()

# configure all the actions
grp_action = parser.add_mutually_exclusive_group()
# JOB Control
grp_action.add_argument('--available', action='store_true',
                        help='Obsolete: Use --jc-status instead')
grp_action.add_argument('--app-info', action='store_true',
                        help='Obsolete:  Use --jc-status instead')
grp_action.add_argument('--webstatus', action='store_true',
                        help='Obsolete:  Use --jc-status instead')

grp_action.add_argument('--jc-create', action='store_true',
                        help='Loads configuration in all jobcontrol process ')
grp_action.add_argument('--jc-kill', action='store_true',
                        help='kill all running processes')
grp_action.add_argument('--jc-destroy', action='store_true',
                        help='delete all jobcontrol configuration')
grp_action.add_argument('--jc-start', action='store_true',
                        help='start all controled processes described in $DAQCONFIG jsonfile variable')
grp_action.add_argument('--jc-restart', action='store_true',
                        help='restart one job with --jobname=name --jobpid=pid --host=hostname')
grp_action.add_argument('--jc-status', action='store_true',
                        help='show the status all controled processes or of the process specified in --name=PROC')
grp_action.add_argument('--jc-info', action='store_true',
                        help='show the status all controled processesof the host specified in --host=Host')
grp_action.add_argument('--jc-appcreate', action='store_true',
                        help='Create all ZDAQ app on all hosts')

#DAQ preparation
grp_action.add_argument('--daq-create', action='store_true',
                        help='Send the CREATE transition to the FDAQ process (i.e parameters loads of all controlled application) ')
grp_action.add_argument('--daq-discover', action='store_true',
                        help='FDAQ scans controlled application and forward CREATE transition to all controlled processes')
grp_action.add_argument('--daq-setparameters', action='store_true',
                        help='send the parameters described in $DAQCONFIG file to the DAQ')
grp_action.add_argument('--daq-getparameters', action='store_true',
                        help='get the parameters described in $DAQCONFIG file to the DAQ')
grp_action.add_argument('--daq-forceState', action='store_true',
                        help='force the sate name of the FDAQ with the --state option, ex --forceState --state=DISCOVERED')
grp_action.add_argument('--daq-services', action='store_true',
                        help='Send INITIALISE/CONFIGURE transition to services application (MDCC,DB,BUILDER mainly)')
grp_action.add_argument('--daq-state', action='store_true',
                        help=' display DAQ state')
# Running
grp_action.add_argument('--daq-initialise', action='store_true',
                        help='Initialise FDAQ, data source discovery and Builder final configuration')
grp_action.add_argument('--daq-configure', action='store_true',
                        help=' Configure FDAQ, front end ASICs configuration')
grp_action.add_argument('--daq-startrun', action='store_true',
                        help=' start the run')
grp_action.add_argument('--daq-stoprun', action='store_true',
                        help=' stop the run')
grp_action.add_argument('--daq-destroy', action='store_true',
                        help='destroy the readout, back to the PREPARED state')
# Status
grp_action.add_argument('--daq-difstatus', action='store_true',
                        help=' display DAQ status of all SDHCAL DIF')
grp_action.add_argument('--daq-tdcstatus', action='store_true',
                        help=' display DAQ status of all FEBCMS TDC')
grp_action.add_argument('--daq-evbstatus', action='store_true',
                        help=' display event builder status')
grp_action.add_argument('--daq-dbstatus', action='store_true',
                        help='get current run and state from db')
# Actions
grp_action.add_argument('--daq-downloaddb', action='store_true',
                        help='download the dbsate specified in --dbstate=state')

#DIF  Calibration
grp_action.add_argument('--dif-setgain', action='store_true',
                        help='change the gain of HARDROC2 and reconfigure chips with --gain=xxx')
grp_action.add_argument('--dif-setthreshold', action='store_true',
                        help='change the threholds of HARDROC2 and reconfigure chips with --B0=xxx --B1=yyy --B2=zzz')
grp_action.add_argument('--dif-ctrlreg', action='store_true',
                        help='set the SDHCAL DIF ctrlregister specified with --ctrlreg=register')

#FEBV1 actions
grp_action.add_argument('--feb-resettdc', action='store_true',
                        help=' Send Reset to all FEB TDC')
grp_action.add_argument('--feb-calibdac', action='store_true',
                        help='Start a PETIROC calibdac run')
grp_action.add_argument('--feb-scurve', action='store_true',
                        help='Start a PETIROC scurve run')
grp_action.add_argument('--feb-setvth', action='store_true',
                        help='change the VTHTIME threshold of PETIROC2 and reconfigure chips with -vth=xxx')
grp_action.add_argument('--feb-setmask', action='store_true',
                        help='change the MASK of PETIROC2reconfigure chips with -mask=xxx')
grp_action.add_argument('--feb-settdcmode', action='store_true',
                        help='change the trigger mode before starting the run with --value=1/0')
grp_action.add_argument('--feb-settdcdelays', action='store_true',
                        help='change the PETIROC mode before starting the run with --active=1-255, --dead=1-255 ')
grp_action.add_argument('--feb-lutcalib', action='store_true',
                        help='Calibrate --tdc=i --channel=k ')
grp_action.add_argument('--feb-lutdraw', action='store_true',
                        help='Calibrate --tdc=i --channel=k ')
grp_action.add_argument('--histo-draw', action='store_true',
                        help='Draw histo --name=histo ')


# TRIGGER MDCC
grp_action.add_argument('--trig-status', action='store_true',
                        help=' display trigger (MDCC) counter status')
grp_action.add_argument('--trig-reset', action='store_true',
                        help=' reset trigger (MDCC) counter')
grp_action.add_argument('--trig-pause', action='store_true',
                        help=' trigger (MDCC) soft veto')
grp_action.add_argument('--trig-resume', action='store_true',
                        help=' release trigger (MDCC) soft veto ')
grp_action.add_argument('--ecal-pause', action='store_true',
                        help=' (Obsolete) Ecal soft veto')
grp_action.add_argument('--ecal-resume', action='store_true',
                        help=' (Obsolete) release Ecal soft veto')
grp_action.add_argument('--trig-spillon', action='store_true',
                        help=' set spill nclock on with --clock=nc (20ns)')
grp_action.add_argument('--trig-spilloff', action='store_true',
                        help=' set spill nclock off with --clock=nc (20ns) ')
grp_action.add_argument('--trig-beam', action='store_true',
                        help=' set beam length to nclock with --clock=nc (20ns) ')
grp_action.add_argument('--trig-spillregister', action='store_true',
                        help=' set the value of the spill register (FEB CMS) (32/64 for beamtest or cosmic) --value=xx ')
grp_action.add_argument('--trig-calibon', action='store_true',
                        help=' set the value of the calibon register (FEB calibration) --value=xx ')
grp_action.add_argument('--trig-calibcount', action='store_true',
                        help=' set the value of the calibcount (FEB calibration) register --value=xx ')
grp_action.add_argument('--trig-rearm', action='store_true',
                        help=' reload calib (FEB calibration)  ')
grp_action.add_argument('--trig-hardreset', action='store_true',
                        help=' send a hard reset to mezzanines ')
grp_action.add_argument('--trig-setregister', action='store_true',
                        help=' set the value of the MDCC register --value=xx --address=yy')
grp_action.add_argument('--trig-getregister', action='store_true',
                        help=' get the value of the MDCC register  --address=yy')
grp_action.add_argument('--trig-tdcreset', action='store_true',
                        help=' hard reset of TDC (FEB) counters')


# Slow Control Managment
grp_action.add_argument('--slc-create', action='store_true',
                        help='Send a CREATE transition to FSLOW app (parsing of configuration)')
grp_action.add_argument('--slc-initialise', action='store_true',
                        help='Send a INITIALISE transition to FSLOW (auto discovery and CREATE transition to all controlled apps) ')
grp_action.add_argument('--slc-configure', action='store_true',
                        help='Send a CONFIGURE transition to FSLOW (configuration of all controlled apps)')
grp_action.add_argument('--slc-start', action='store_true',
                        help='Send a START transition to all monitorApplication controlled ')
grp_action.add_argument('--slc-stop', action='store_true',
                        help='Send a STOP transition to all monitorApplication controlled')
# LV
grp_action.add_argument(
    '--slc-lvon', action='store_true', help='put Zup LV ON')
grp_action.add_argument(
    '--slc-lvoff', action='store_true', help='put Zup LV OFF')
grp_action.add_argument(
    '--slc-lvstatus', action='store_true', help='Dump LV status')

#grp_action.add_argument('--slc-loadreferences',action='store_true',help='load in the wiener crate chambers references voltage download from DB')
grp_action.add_argument('--slc-hvstatus', action='store_true',
                        help='display hvstatus of all channel of the wiener crate')

#grp_action.add_argument('--slc-setperiod',action='store_true',help='set the readout period of Wiener and BMP with --period=second(s)')
grp_action.add_argument('--slc-vset', action='store_true',
                        help='set the voltage V of channel i to k with --first=i --last=k --voltage=V')
grp_action.add_argument('--slc-iset', action='store_true',
                        help='set the current limit I (microA) of channel i to k with --first=i --last=k --current=I')
grp_action.add_argument('--slc-rampup', action='store_true',
                        help='set the ramp (V/S) of channel i to k with --first=i --last=k --ramp=r')

grp_action.add_argument('--slc-hvon', action='store_true',
                        help='set the voltage ON  of channel i to k with --first=i --last=k ')
grp_action.add_argument('--slc-hvoff', action='store_true',
                        help='set the voltage OFF  of channel i to k with --first=i --last=k ')
grp_action.add_argument('--slc-clearalarm', action='store_true',
                        help='Clear alarm  of channel i to k with --first=i --last=k ')


# Environmental
grp_action.add_argument('--slc-ptstatus', action='store_true',
                        help='display the P and T from the BMP183 readout')
grp_action.add_argument('--slc-humstatus', action='store_true',
                        help='display the Humidity and T from the HIH8000 readout')
grp_action.add_argument('--slc-ptcor', action='store_true',
                        help='display the needed voltage for --v0=v --p0=p (mbar) --t0=t (K)')


#grp_action.add_argument('--slc-store',action='store_true',help='start the data storage in the mysql DB at period p  with --period=p (s) ')
#grp_action.add_argument('--slc-store-stop',action='store_true',help='stop the data storage in the mysql DB ')
#grp_action.add_argument('--slc-check',action='store_true',help='start the voltage tuning wrt references at period p  with --period=p (s) ')
#grp_action.add_argument('--slc-check-stop',action='store_true',help='stop the voltage tuning ')


# Arguments
parser.add_argument('--config', action='store', dest='config',
                    default=None, help='json config file')
parser.add_argument('--socks', action='store', type=int,
                    dest='sockport', default=None, help='use SOCKS port ')
parser.add_argument('--dbstate', action='store', default=None,
                    dest='dbstate', help='set the dbstate')
parser.add_argument('--ctrlreg', action='store', default=None,
                    dest='ctrlreg', help='set the Control register in hexa')
parser.add_argument('--version', action='version', version='%(prog)s 1.0')
parser.add_argument('--state', action='store', type=str,
                    default=None, dest='fstate', help='set the Daq state')
parser.add_argument('--clock', action='store', type=int, default=None,
                    dest='clock', help='set the number of 20 ns clock')
parser.add_argument('--directory', action='store', type=str,
                    dest='directory', default=None, help='shm publisher directory')
parser.add_argument('--vth', action='store', type=int,
                    default=None, dest='vth', help='set the vth for chips')
parser.add_argument('--mask', action='store', type=int,
                    default=None, dest='mask', help='set the mask for chips')
parser.add_argument('--gain', action='store', type=int,
                    default=None, dest='gain', help='set the gain for chips')
parser.add_argument('--B0', action='store', type=int,
                    default=None, dest='B0', help='set the B0 for chips')
parser.add_argument('--B1', action='store', type=int,
                    default=None, dest='B1', help='set the B1 for chips')
parser.add_argument('--B2', action='store', type=int,
                    default=None, dest='B2', help='set the B2 for chips')

parser.add_argument('--v0', action='store', type=float,
                    default=None, dest='v0', help='reference hv')
parser.add_argument('--p0', action='store', type=float,
                    default=None, dest='p0', help='reference P')
parser.add_argument('--t0', action='store', type=float,
                    default=None, dest='t0', help='reference T')

parser.add_argument('--tdc', action='store', type=int,
                    default=None, dest='tdc', help='set the tdc process')

# Slow
parser.add_argument('--channel', action='store', type=int,
                    default=None, dest='channel', help='set the hvchannel')
parser.add_argument('--first', action='store', type=int,
                    default=None, dest='first', help='set the first hvchannel')
parser.add_argument('--last', action='store', type=int,
                    default=None, dest='last', help='set the last hvchannel')
parser.add_argument('--step', action='store', type=int, default=None,
                    dest='step', help='set the step of the calibration')
parser.add_argument('--voltage', action='store', type=float,
                    default=None, dest='voltage', help='set the hv voltage')
parser.add_argument('--current', action='store', type=float,
                    default=None, dest='current', help='set the hv current')
parser.add_argument('--ramp', action='store', type=float,
                    default=None, dest='ramp', help='set the hv ramp')

parser.add_argument('--account', action='store', default=None,
                    dest='account', help='set the Slow Control mysql account')
parser.add_argument('--period', action='store', type=int, default=None,
                    dest='period', help='set the temporistaion period (s)')

parser.add_argument('--spillon', action='store', type=float,
                    default=None, dest='spillon', help='spill on')
parser.add_argument('--spilloff', action='store', type=float,
                    default=None, dest='spilloff', help='spilloff')

# Job
parser.add_argument('--lines', action='store', type=int, default=None,
                    dest='lines', help='set the number of lines to be dump')
parser.add_argument('--host', action='store', dest='host',
                    default=None, help='host for log')
parser.add_argument('--name', action='store', dest='name',
                    default=None, help='application name')
parser.add_argument('--jobname', action='store',
                    dest='jobname', default=None, help='job name')
parser.add_argument('--jobpid', action='store', type=int,
                    dest='jobpid', default=None, help='job pid')
parser.add_argument('--value', action='store', type=int,
                    dest='value', default=None, help='value to pass')
parser.add_argument('--address', action='store', type=int,
                    dest='address', default=None, help='address to pass')
parser.add_argument('--active', action='store', type=int,
                    dest='active', default=None, help='active time of Petiroc')
parser.add_argument('--dead', action='store', type=int,
                    dest='dead', default=None, help='dead time of Petiroc')
parser.add_argument('--asic', action='store', type=int,
                    dest='asic', default=None, help='asic header of Petiroc')
parser.add_argument('--feb', action='store', type=int,
                    dest='feb', default=None, help='FEB id')
parser.add_argument('--dbversion', action='store', type=int,
                    dest='dbversion', default=None, help='DB state version')
parser.add_argument('-v', '--verbose', action='store_true',
                    default=False, help='Raw Json output')

parser.add_argument('--comment', action='store', default=None,
                    dest='comment', help=' Comment for start run')


account=os.getenv("MGDBLOGIN","NONE")
if (account == "NONE"):
    print "The ENV varaible MGDBLOGIN=user/pwd@host:port@dbname mut be set"
    exit(0)

config=os.getenv("DAQMONGO","NONE")
if (config == "NONE"):
    print "The ENV varaible name:version mut be set"
    exit(0)

fdc=febrc.febRC(account,config)
fdc.Connect()
fdc.updateInfo(True,True)

if len(sys.argv)==1:
    parser.print_help(sys.stderr)
    sys.exit(1)
results = parser.parse_args()

