import os
Arm=os.uname()[4]=='armv7l' or os.uname()[4]=='armv6l'
plist=['wiener/SConscript','genesys/SConscript','zup/SConscript','mgstore/SConscript']
if (Arm):
   plist.append('bmp/SConscript')
   plist.append('hih/SConscript')
else:
   plist.append('syx27/SConscript')

SConscript(plist)
