name: angular_app
description: Tour of Heroes
version: 0.0.1

environment:
  sdk: '>=2.2.0 <3.0.0'

dependencies:
  angular: ^6.0.0-alpha
  angular_forms: ^2.1.0
  http: ^0.12.1
  uri: ^0.11.3+1 
  mongo_dart: ^0.4.0
  ansicolor: ^1.0.2
  args: ^1.0.0
  logging: ^0.11.4

dev_dependencies:
  angular_test: ^2.3.1
  build_runner: ^1.5.1
  build_test: ^0.10.8
  build_web_compilers: ^2.1.0
  test: ^1.6.4
