import os
Arm=os.uname()[4]=='armv7l'


if (Arm):
    SConscript(['Bmp/SConscript',
	        'Pmr/SConscript',
	        'Dif/SConscript',
	        'FebInj/SConscript',
                'Ftdi/SConscript',
                'Genesys/SConscript',
                'GPIO/SConscript',
                'hih8000/SConscript',
                'Mdcc/SConscript',
                'MdccEcal/SConscript',
                'N1470/SConscript',
                'Sdcc/SConscript',
                'Zup/SConscript',
                'Wiener/SConscript',
                'MgRoc/SConscript',
                'MPI/SConscript',
                'utils/netLink/SConscript'
    ])
else:
    plist=['Dif/SConscript',
                'Ftdi/SConscript',
	        'Pmr/SConscript',
	        'Dif/SConscript',
                'Genesys/SConscript',
                'Caen/SConscript',
                'Mdcc/SConscript',
                'MdccEcal/SConscript',
                'N1470/SConscript',
                'Sdcc/SConscript',
                'Zup/SConscript',
                'Wiener/SConscript',
                'MgRoc/SConscript',
                'MPI/SConscript',
                'utils/netLink/SConscript'
    ]
    Use_Mysql=os.path.exists("/usr/include/mysql")
    if (Use_Mysql):
        plist.append('TmvDb/SConscript')
    SConscript(plist)
