# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'jobdialog.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_JobDialog(object):
    def setupUi(self, JobDialog):
        JobDialog.setObjectName("JobDialog")
        JobDialog.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(JobDialog)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setAutoFillBackground(True)
        self.groupBox_3.setObjectName("groupBox_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.groupBox_3)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pbJCCREATE = QtWidgets.QPushButton(self.groupBox_3)
        self.pbJCCREATE.setObjectName("pbJCCREATE")
        self.horizontalLayout_3.addWidget(self.pbJCCREATE)
        self.pbJCSTART = QtWidgets.QPushButton(self.groupBox_3)
        self.pbJCSTART.setObjectName("pbJCSTART")
        self.horizontalLayout_3.addWidget(self.pbJCSTART)
        self.pbJCKILL = QtWidgets.QPushButton(self.groupBox_3)
        self.pbJCKILL.setObjectName("pbJCKILL")
        self.horizontalLayout_3.addWidget(self.pbJCKILL)
        self.pbJCAPPCREATE = QtWidgets.QPushButton(self.groupBox_3)
        self.pbJCAPPCREATE.setMinimumSize(QtCore.QSize(161, 0))
        self.pbJCAPPCREATE.setObjectName("pbJCAPPCREATE")
        self.horizontalLayout_3.addWidget(self.pbJCAPPCREATE)
        self.pbJCDESTROY = QtWidgets.QPushButton(self.groupBox_3)
        self.pbJCDESTROY.setObjectName("pbJCDESTROY")
        self.horizontalLayout_3.addWidget(self.pbJCDESTROY)
        self.pbJCINFO = QtWidgets.QPushButton(self.groupBox_3)
        self.pbJCINFO.setObjectName("pbJCINFO")
        self.horizontalLayout_3.addWidget(self.pbJCINFO)
        self.pbJOBLOGS = QtWidgets.QPushButton(self.groupBox_3)
        self.pbJOBLOGS.setObjectName("pbJOBLOGS")
        self.horizontalLayout_3.addWidget(self.pbJOBLOGS)
        self.verticalLayout.addWidget(self.groupBox_3)
        self.groupBox_4 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_4.setAutoFillBackground(True)
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBox_10 = QtWidgets.QGroupBox(self.groupBox_4)
        self.groupBox_10.setMaximumSize(QtCore.QSize(16777215, 64))
        self.groupBox_10.setAutoFillBackground(True)
        self.groupBox_10.setFlat(False)
        self.groupBox_10.setObjectName("groupBox_10")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox_10)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.cbVERBOSE = QtWidgets.QCheckBox(self.groupBox_10)
        self.cbVERBOSE.setObjectName("cbVERBOSE")
        self.horizontalLayout.addWidget(self.cbVERBOSE)
        self.cbPROCESSONLY = QtWidgets.QCheckBox(self.groupBox_10)
        self.cbPROCESSONLY.setObjectName("cbPROCESSONLY")
        self.horizontalLayout.addWidget(self.cbPROCESSONLY)
        spacerItem = QtWidgets.QSpacerItem(561, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.laCMD = QtWidgets.QLabel(self.groupBox_10)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.laCMD.setFont(font)
        self.laCMD.setObjectName("laCMD")
        self.horizontalLayout.addWidget(self.laCMD)
        self.verticalLayout_2.addWidget(self.groupBox_10)
        self.tbJCINFO = QtWidgets.QTextBrowser(self.groupBox_4)
        self.tbJCINFO.setObjectName("tbJCINFO")
        self.verticalLayout_2.addWidget(self.tbJCINFO)
        self.verticalLayout.addWidget(self.groupBox_4)
        JobDialog.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(JobDialog)
        self.statusbar.setObjectName("statusbar")
        JobDialog.setStatusBar(self.statusbar)

        self.retranslateUi(JobDialog)
        QtCore.QMetaObject.connectSlotsByName(JobDialog)

    def retranslateUi(self, JobDialog):
        _translate = QtCore.QCoreApplication.translate
        JobDialog.setWindowTitle(_translate("JobDialog", "JOB CONTROL"))
        self.groupBox_3.setTitle(_translate("JobDialog", "Control"))
        self.pbJCCREATE.setText(_translate("JobDialog", "CREATE"))
        self.pbJCSTART.setText(_translate("JobDialog", "START"))
        self.pbJCKILL.setText(_translate("JobDialog", "KILL"))
        self.pbJCAPPCREATE.setText(_translate("JobDialog", "Application CREATE"))
        self.pbJCDESTROY.setText(_translate("JobDialog", "DESTROY"))
        self.pbJCINFO.setText(_translate("JobDialog", "INFO"))
        self.pbJOBLOGS.setText(_translate("JobDialog", "LOGS"))
        self.groupBox_4.setTitle(_translate("JobDialog", "Status"))
        self.groupBox_10.setTitle(_translate("JobDialog", "Details"))
        self.cbVERBOSE.setText(_translate("JobDialog", "Verbose"))
        self.cbPROCESSONLY.setText(_translate("JobDialog", "Process Only"))
        self.laCMD.setText(_translate("JobDialog", "No Last command executed"))

