# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1003, 620)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(211, 215, 207))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(233, 235, 231))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(105, 107, 103))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(141, 143, 138))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(211, 215, 207))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(233, 235, 231))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(211, 215, 207))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(233, 235, 231))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(105, 107, 103))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(141, 143, 138))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(211, 215, 207))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(233, 235, 231))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(105, 107, 103))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(211, 215, 207))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(233, 235, 231))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(105, 107, 103))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(141, 143, 138))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(105, 107, 103))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(105, 107, 103))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(211, 215, 207))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(211, 215, 207))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(211, 215, 207))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        MainWindow.setPalette(palette)
        MainWindow.setAutoFillBackground(True)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setAutoFillBackground(True)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(self.tab)
        self.groupBox.setMaximumSize(QtCore.QSize(555555, 150))
        self.groupBox.setAutoFillBackground(True)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.lwMONGO = QtWidgets.QListWidget(self.groupBox)
        self.lwMONGO.setObjectName("lwMONGO")
        self.gridLayout_2.addWidget(self.lwMONGO, 0, 0, 2, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 0, 1, 1, 1)
        self.pbSHOWCONFIG = QtWidgets.QPushButton(self.groupBox)
        self.pbSHOWCONFIG.setObjectName("pbSHOWCONFIG")
        self.gridLayout_2.addWidget(self.pbSHOWCONFIG, 0, 2, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(276, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 0, 3, 1, 1)
        self.laDAQMONGO = QtWidgets.QLabel(self.groupBox)
        self.laDAQMONGO.setObjectName("laDAQMONGO")
        self.gridLayout_2.addWidget(self.laDAQMONGO, 1, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(159, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 1, 2, 1, 1)
        self.pbCREATEACCESS = QtWidgets.QPushButton(self.groupBox)
        self.pbCREATEACCESS.setObjectName("pbCREATEACCESS")
        self.gridLayout_2.addWidget(self.pbCREATEACCESS, 1, 3, 1, 1)
        self.verticalLayout.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_2.setAutoFillBackground(True)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(393, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 0, 1, 1, 1)
        self.laMONGOACCOUNT = QtWidgets.QLabel(self.groupBox_2)
        self.laMONGOACCOUNT.setObjectName("laMONGOACCOUNT")
        self.gridLayout.addWidget(self.laMONGOACCOUNT, 0, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(393, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem3, 1, 1, 1, 1)
        self.laDAQSETUP = QtWidgets.QLabel(self.groupBox_2)
        self.laDAQSETUP.setObjectName("laDAQSETUP")
        self.gridLayout.addWidget(self.laDAQSETUP, 1, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(393, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem4, 2, 1, 1, 1)
        self.lcdSOCKPORT = QtWidgets.QLCDNumber(self.groupBox_2)
        self.lcdSOCKPORT.setObjectName("lcdSOCKPORT")
        self.gridLayout.addWidget(self.lcdSOCKPORT, 2, 2, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.groupBox_9 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_9.setAutoFillBackground(True)
        self.groupBox_9.setObjectName("groupBox_9")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.groupBox_9)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pbJOBCONTROL = QtWidgets.QPushButton(self.groupBox_9)
        self.pbJOBCONTROL.setObjectName("pbJOBCONTROL")
        self.horizontalLayout_2.addWidget(self.pbJOBCONTROL)
        self.pbDAQ = QtWidgets.QPushButton(self.groupBox_9)
        self.pbDAQ.setObjectName("pbDAQ")
        self.horizontalLayout_2.addWidget(self.pbDAQ)
        spacerItem5 = QtWidgets.QSpacerItem(756, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem5)
        self.verticalLayout.addWidget(self.groupBox_9)
        spacerItem6 = QtWidgets.QSpacerItem(20, 272, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem6)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_3.setAutoFillBackground(True)
        self.groupBox_3.setObjectName("groupBox_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.groupBox_3)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pbJCCREATE = QtWidgets.QPushButton(self.groupBox_3)
        self.pbJCCREATE.setObjectName("pbJCCREATE")
        self.horizontalLayout_3.addWidget(self.pbJCCREATE)
        self.pbJCSTART = QtWidgets.QPushButton(self.groupBox_3)
        self.pbJCSTART.setObjectName("pbJCSTART")
        self.horizontalLayout_3.addWidget(self.pbJCSTART)
        self.pbJCKILL = QtWidgets.QPushButton(self.groupBox_3)
        self.pbJCKILL.setObjectName("pbJCKILL")
        self.horizontalLayout_3.addWidget(self.pbJCKILL)
        self.pbJCAPPCREATE = QtWidgets.QPushButton(self.groupBox_3)
        self.pbJCAPPCREATE.setMinimumSize(QtCore.QSize(161, 0))
        self.pbJCAPPCREATE.setObjectName("pbJCAPPCREATE")
        self.horizontalLayout_3.addWidget(self.pbJCAPPCREATE)
        self.pbJCDESTROY = QtWidgets.QPushButton(self.groupBox_3)
        self.pbJCDESTROY.setObjectName("pbJCDESTROY")
        self.horizontalLayout_3.addWidget(self.pbJCDESTROY)
        self.pbJCINFO = QtWidgets.QPushButton(self.groupBox_3)
        self.pbJCINFO.setObjectName("pbJCINFO")
        self.horizontalLayout_3.addWidget(self.pbJCINFO)
        self.verticalLayout_5.addWidget(self.groupBox_3)
        self.groupBox_4 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_4.setAutoFillBackground(True)
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBox_10 = QtWidgets.QGroupBox(self.groupBox_4)
        self.groupBox_10.setMaximumSize(QtCore.QSize(16777215, 64))
        self.groupBox_10.setAutoFillBackground(True)
        self.groupBox_10.setFlat(False)
        self.groupBox_10.setObjectName("groupBox_10")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox_10)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.cbVERBOSE = QtWidgets.QCheckBox(self.groupBox_10)
        self.cbVERBOSE.setObjectName("cbVERBOSE")
        self.horizontalLayout.addWidget(self.cbVERBOSE)
        self.cbPROCESSONLY = QtWidgets.QCheckBox(self.groupBox_10)
        self.cbPROCESSONLY.setObjectName("cbPROCESSONLY")
        self.horizontalLayout.addWidget(self.cbPROCESSONLY)
        spacerItem7 = QtWidgets.QSpacerItem(561, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem7)
        self.verticalLayout_2.addWidget(self.groupBox_10)
        self.tbJCINFO = QtWidgets.QTextBrowser(self.groupBox_4)
        self.tbJCINFO.setObjectName("tbJCINFO")
        self.verticalLayout_2.addWidget(self.tbJCINFO)
        self.verticalLayout_5.addWidget(self.groupBox_4)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.tab_3)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.groupBox_6 = QtWidgets.QGroupBox(self.tab_3)
        self.groupBox_6.setAutoFillBackground(True)
        self.groupBox_6.setObjectName("groupBox_6")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_6)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.groupBox_5 = QtWidgets.QGroupBox(self.groupBox_6)
        self.groupBox_5.setMaximumSize(QtCore.QSize(16777215, 110))
        self.groupBox_5.setObjectName("groupBox_5")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.groupBox_5)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.pbQUERYSTATE = QtWidgets.QPushButton(self.groupBox_5)
        self.pbQUERYSTATE.setObjectName("pbQUERYSTATE")
        self.horizontalLayout_5.addWidget(self.pbQUERYSTATE)
        spacerItem8 = QtWidgets.QSpacerItem(276, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem8)
        self.lwMONGO_2 = QtWidgets.QListWidget(self.groupBox_5)
        self.lwMONGO_2.setObjectName("lwMONGO_2")
        self.horizontalLayout_5.addWidget(self.lwMONGO_2)
        self.pbDOWNLOADDB = QtWidgets.QPushButton(self.groupBox_5)
        self.pbDOWNLOADDB.setObjectName("pbDOWNLOADDB")
        self.horizontalLayout_5.addWidget(self.pbDOWNLOADDB)
        self.verticalLayout_3.addWidget(self.groupBox_5)
        self.groupBox_7 = QtWidgets.QGroupBox(self.groupBox_6)
        self.groupBox_7.setObjectName("groupBox_7")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.groupBox_7)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.leCTRLREG = QtWidgets.QLineEdit(self.groupBox_7)
        self.leCTRLREG.setObjectName("leCTRLREG")
        self.horizontalLayout_6.addWidget(self.leCTRLREG)
        spacerItem9 = QtWidgets.QSpacerItem(307, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem9)
        self.pbCTRLREG = QtWidgets.QPushButton(self.groupBox_7)
        self.pbCTRLREG.setObjectName("pbCTRLREG")
        self.horizontalLayout_6.addWidget(self.pbCTRLREG)
        self.verticalLayout_3.addWidget(self.groupBox_7)
        self.verticalLayout_6.addWidget(self.groupBox_6)
        self.groupBox_8 = QtWidgets.QGroupBox(self.tab_3)
        self.groupBox_8.setAutoFillBackground(True)
        self.groupBox_8.setObjectName("groupBox_8")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.groupBox_8)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.pbDAQINITIALISE = QtWidgets.QPushButton(self.groupBox_8)
        self.pbDAQINITIALISE.setObjectName("pbDAQINITIALISE")
        self.horizontalLayout_7.addWidget(self.pbDAQINITIALISE)
        self.pbDAQCONFIGURE = QtWidgets.QPushButton(self.groupBox_8)
        self.pbDAQCONFIGURE.setObjectName("pbDAQCONFIGURE")
        self.horizontalLayout_7.addWidget(self.pbDAQCONFIGURE)
        self.pbDAQSTART = QtWidgets.QPushButton(self.groupBox_8)
        self.pbDAQSTART.setObjectName("pbDAQSTART")
        self.horizontalLayout_7.addWidget(self.pbDAQSTART)
        self.pbDAQSTOP = QtWidgets.QPushButton(self.groupBox_8)
        self.pbDAQSTOP.setObjectName("pbDAQSTOP")
        self.horizontalLayout_7.addWidget(self.pbDAQSTOP)
        self.pbDAQDESTROY = QtWidgets.QPushButton(self.groupBox_8)
        self.pbDAQDESTROY.setObjectName("pbDAQDESTROY")
        self.horizontalLayout_7.addWidget(self.pbDAQDESTROY)
        self.pbDAQSTATUS = QtWidgets.QPushButton(self.groupBox_8)
        self.pbDAQSTATUS.setObjectName("pbDAQSTATUS")
        self.horizontalLayout_7.addWidget(self.pbDAQSTATUS)
        self.verticalLayout_6.addWidget(self.groupBox_8)
        spacerItem10 = QtWidgets.QSpacerItem(20, 166, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem10)
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.tabWidget.addTab(self.tab_4, "")
        self.verticalLayout_4.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "DAQ settings selection"))
        self.label_4.setText(_translate("MainWindow", "DAQ MONGO Selection"))
        self.pbSHOWCONFIG.setText(_translate("MainWindow", "Show it"))
        self.laDAQMONGO.setText(_translate("MainWindow", "NotSet"))
        self.pbCREATEACCESS.setText(_translate("MainWindow", "Create Acccess"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Environment settings"))
        self.label.setText(_translate("MainWindow", "MONGODB"))
        self.laMONGOACCOUNT.setText(_translate("MainWindow", "acqilc/XXX@lyocmsmux:37377/TOMOROC"))
        self.label_3.setText(_translate("MainWindow", "Experiment"))
        self.laDAQSETUP.setText(_translate("MainWindow", "LeNomedeMonSeup"))
        self.label_2.setText(_translate("MainWindow", "Sock port"))
        self.groupBox_9.setTitle(_translate("MainWindow", "Actions"))
        self.pbJOBCONTROL.setText(_translate("MainWindow", "Job Control..."))
        self.pbDAQ.setText(_translate("MainWindow", "DAQ..."))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "DAQ Settings"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Control"))
        self.pbJCCREATE.setText(_translate("MainWindow", "CREATE"))
        self.pbJCSTART.setText(_translate("MainWindow", "START"))
        self.pbJCKILL.setText(_translate("MainWindow", "KILL"))
        self.pbJCAPPCREATE.setText(_translate("MainWindow", "Application CREATE"))
        self.pbJCDESTROY.setText(_translate("MainWindow", "DESTROY"))
        self.pbJCINFO.setText(_translate("MainWindow", "INFO"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Status"))
        self.groupBox_10.setTitle(_translate("MainWindow", "Details"))
        self.cbVERBOSE.setText(_translate("MainWindow", "Verbose"))
        self.cbPROCESSONLY.setText(_translate("MainWindow", "Process Only"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Process control"))
        self.groupBox_6.setTitle(_translate("MainWindow", "Settings"))
        self.groupBox_5.setTitle(_translate("MainWindow", "Database state"))
        self.pbQUERYSTATE.setText(_translate("MainWindow", "Query"))
        self.pbDOWNLOADDB.setText(_translate("MainWindow", "Download"))
        self.groupBox_7.setTitle(_translate("MainWindow", "Control Register"))
        self.pbCTRLREG.setText(_translate("MainWindow", "Set"))
        self.groupBox_8.setTitle(_translate("MainWindow", "Control"))
        self.pbDAQINITIALISE.setText(_translate("MainWindow", "Initialise"))
        self.pbDAQCONFIGURE.setText(_translate("MainWindow", "Configure"))
        self.pbDAQSTART.setText(_translate("MainWindow", "Start"))
        self.pbDAQSTOP.setText(_translate("MainWindow", "Stop"))
        self.pbDAQDESTROY.setText(_translate("MainWindow", "Destroy"))
        self.pbDAQSTATUS.setText(_translate("MainWindow", "Status"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Acquisition"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "Analyse"))

