import os
Arm=os.uname()[4]=='armv7l'


if (Arm):
    SConscript(['Builder/SConscript',
                'Bmp/SConscript',
                'FebInj/SConscript',
                'GPIO/SConscript',
                'hih8000/SConscript',
                'ConfigurationDB/SConscript',
                'Control/SConscript',
		'Dif/SConscript',
                'Gric/SConscript',	
                'DIF/SConscript',
                'FebCms/SConscript',
                'Genesys/SConscript',
                'Mdcc/SConscript',
                'MdccEcal/SConscript',
                'monitoring/SConscript',
                'Sdcc/SConscript',
                'Zup/SConscript',
                'Wiener/SConscript'
    ])
else:
    SConscript(['Builder/SConscript',
                'Caen/SConscript',
                'ConfigurationDB/SConscript',
                'Control/SConscript',
		'Dif/SConscript',
                'Gric/SConscript',	
                'DIF/SConscript',
                'FebCms/SConscript',
                'Genesys/SConscript',
                'Mdcc/SConscript',
                'MdccEcal/SConscript',
                'monitoring/SConscript',
                'N1470/SConscript',
                'Sdcc/SConscript',
                'Zup/SConscript',
                'Wiener/SConscript'
    ])
