#!/usr/bin/env python
import os
import socks
import socket
import httplib
import urllib
import urllib2
from urllib2 import URLError, HTTPError
import json
from copy import deepcopy
import base64
import time
import argparse
import requests
import MongoRoc as mg



# create the default access
f=open("/etc/.mongoroc.json")
s=json.loads(f.read())
_wdd=mg.MongoRoc(s["host"],s["port"],s["db"],s["user"],s["pwd"])
f.close()



parser = argparse.ArgumentParser()

# configure all the actions
grp_action = parser.add_mutually_exclusive_group()
grp_action.add_argument('--download', action='store_true',
                        help='download the state specified in --state=state --version=version')
# Arguments
parser.add_argument('--version', action='store',type=int,default=1,dest='version',help='DB state version' )
parser.add_argument('--state', action='store', type=str,
                    default=None, dest='state', help='DB State')

results = parser.parse_args()


# Analyse results
# analyse the command
lcgi = {}
r_cmd = None
if (results.download):
    r_cmd = 'download'
    if (results.state == None):
        print 'Please specify the state --state=name'
        exit(0)
    if (results.version == None):
        print 'Please specify the state --version=ver'
        exit(0)
    _wdd.download(results.state,results.version)
    exit(0)
