import os

plist=['sdhcal/SConscript','shmwriter/SConscript','tdcwriter/SConscript','monitor/SConscript']
if (os.getenv("ROOTSYS")!=None):
    plist.append('rootwriter/SConscript')
if (os.getenv("LCIODIR")!=None):
    plist.append('lciowriter/SConscript')
SConscript(plist)
